apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: redis
  targetCPUUtilizationPercentage: 50