apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- statefulset.yaml
- service.yaml
# - hpa.yaml
commonLabels:
  app: redis
images:
- name: redis
  newName: redis
  newTag: 6.0.1-alpine
configMapGenerator:
- name: redis-config
  files:
    - config/master.conf
    - config/slave.conf
    - config/init.sh
generatorOptions:
  disableNameSuffixHash: true