# Generated by Django 3.0.5 on 2020-04-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similarity', models.DecimalField(decimal_places=7, max_digits=8)),
                ('formula', models.CharField(choices=[('cosine', 'cosine'), ('pearson', 'pearson')], default='cosine', max_length=16)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_source', to='customers.Customer')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_target', to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similarity', models.DecimalField(decimal_places=7, max_digits=8)),
                ('formula', models.CharField(choices=[('cosine', 'cosine'), ('pearson', 'pearson')], default='cosine', max_length=16)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_source', to='companies.Company')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_target', to='companies.Company')),
            ],
        ),
        migrations.AddIndex(
            model_name='customersimilarity',
            index=models.Index(fields=['source_id', 'formula'], name='scores_cust_source__3e91b7_idx'),
        ),
        migrations.AddIndex(
            model_name='customersimilarity',
            index=models.Index(fields=['-similarity'], name='scores_cust_similar_96f530_idx'),
        ),
        migrations.AddIndex(
            model_name='companysimilarity',
            index=models.Index(fields=['source_id', 'formula'], name='scores_comp_source__6d6129_idx'),
        ),
        migrations.AddIndex(
            model_name='companysimilarity',
            index=models.Index(fields=['-similarity'], name='scores_comp_similar_895e1c_idx'),
        ),
    ]
