# Generated by Django 3.0.5 on 2020-04-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20200422_1035'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companysimilarity',
            constraint=models.UniqueConstraint(fields=('source_id', 'target_id'), name='unique_company_sim'),
        ),
        migrations.AddConstraint(
            model_name='customersimilarity',
            constraint=models.UniqueConstraint(fields=('source_id', 'target_id'), name='unique_customer_sim'),
        ),
    ]
