# Generated by Django 3.0.5 on 2020-04-22 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('companies', '0001_initial'),
        ('scores', '0003_auto_20200422_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysimilarity',
            name='source',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sim_source', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='companysimilarity',
            name='target',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sim_target', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='customersimilarity',
            name='source',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sim_source', to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='customersimilarity',
            name='target',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sim_target', to='customers.Customer'),
        ),
    ]
