# Generated by Django 3.0.5 on 2020-04-21 09:05

from django.db import migrations, models
import job_recommender.algo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('sim_company', 'sim_company'), ('sim_customer', 'sim_customer')], default='sim_company', max_length=64)),
                ('version', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('algo', models.FileField(upload_to=job_recommender.algo.models.algo_directory_path)),
            ],
        ),
        migrations.AddConstraint(
            model_name='algo',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_algo_name'),
        ),
    ]
