apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
configMapGenerator:
- name: deployment-params
  envs: [params.env]
secretGenerator:
- name: deployment-secrets
  envs: [secrets.env]
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: GCP_PRJECT_ID
  objref:
    kind: ConfigMap
    name: deployment-params
    apiVersion: v1
  fieldref:
    fieldpath: data.GCP_PRJECT_ID
- name: GCP_REGION
  objref:
    kind: ConfigMap
    name: deployment-params
    apiVersion: v1
  fieldref:
    fieldpath: data.GCP_REGION
- name: GCP_CLOUDSQL_INSTANCE
  objref:
    kind: ConfigMap
    name: deployment-params
    apiVersion: v1
  fieldref:
    fieldpath: data.GCP_CLOUDSQL_INSTANCE