apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- issuer.yaml
- certificates.yaml
secretGenerator:
- name: gcp-ingress-credentials
  files:
    - secret/dns01-solver-credentials.json
generatorOptions:
  disableNameSuffixHash: true
