apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: django
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: django
  targetCPUUtilizationPercentage: 50

# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: django
# spec:
#   maxReplicas: 10
#   minReplicas: 1
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: django
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       targetAverageUtilization: 50
#   - type: Resource
#     resource:
#       name: memory
#       targetAverageValue: 100Mi
