apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
# - hpa.yaml
patchesStrategicMerge:
- deployment-var.yaml
commonLabels:
  app: django
images:
- name: job_recommender
  newName: gcr.io/banded-totality-247701/job_recommender
  newTag: 'latest'
- name: gce-proxy
  newName: gcr.io/cloudsql-docker/gce-proxy
  newTag: '1.17'
configMapGenerator:
- name: django-config
  files:
    - config/start.sh
    - config/create-ssh-tunnel.sh
secretGenerator:
- name: gcp-credentials
  files:
    - secret/cloudsql-credentials.json
    - secret/storage-credentials.json
- name: gcp-cloudsql-certs
  files:
    - secret/cloudsql-certs/client-cert.pem
    - secret/cloudsql-certs/client-key.pem
    - secret/cloudsql-certs/server-ca.pem
- name: mysql-sshkey
  files:
    - secret/mysql-sshkey
    - secret/mysql-sshkey.pub
    - secret/mysql-sshknown_hosts
generatorOptions:
  disableNameSuffixHash: true