apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
  annotations:
      cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: django
