apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- statefulset.yaml
- service.yaml
commonLabels:
  app: sentinel
images:
- name: redis
  newName: redis
  newTag: 6.0.1-alpine
configMapGenerator:
- name: sentinel-config
  files:
    - config/sentinel.conf
    - config/init.sh
generatorOptions:
  disableNameSuffixHash: true