# Generated by Django 3.0.5 on 2020-04-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landing', models.PositiveIntegerField(default=0)),
                ('review', models.PositiveIntegerField(default=0)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('interview', models.PositiveIntegerField(default=0)),
                ('job_posting', models.PositiveIntegerField(default=0)),
                ('job_posting_detail', models.PositiveIntegerField(default=0)),
                ('benefit', models.PositiveIntegerField(default=0)),
                ('analytics', models.PositiveIntegerField(default=0)),
                ('etc', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
