apiVersion: v1
kind: Service
metadata:
   name: mysql
spec:
   ports:
   - name: mysql
     protocol: TCP
     port: 3306
     targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
subsets:
  - addresses:
      - ip: 192.168.64.1
    ports:
      - name: mysql
        port: 3306

# kind: Service
# apiVersion: v1
# metadata:
#   name: mysql
# spec:
#   type: ExternalName
#   externalName: minikube.host