apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: "ssd"
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: postgres-pvc
  gcePersistentDisk:
    pdName: postgres
    fsType: ext4