apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  init.sh: "#!/bin/bash\nset -e\n\nif [[ ${HOSTNAME} == 'postgres-0' ]]; then\n  cp
    /etc/master.conf /etc/master_or_replica.conf\n\n  psql -v ON_ERROR_STOP=1 --username
    \"$POSTGRES_USER\" --dbname \"$POSTGRES_DB\" <<-EOSQL\n  \tCREATE ROLE replication
    WITH REPLICATION PASSWORD '$REPLICATION_PASSWORD' LOGIN\n  EOSQL\n\nelse\n  cp
    /etc/replica.conf /etc/master_or_replica.conf\n\n  echo \"Running pg_basebackup
    to catch up replication server...\";\n  pg_basebackup -R -h postgres -D \"$PGDATA\"
    -P -U replication; \n  chown -R postgres:postgres $PGDATA;\nfi"
  master.conf: |
    wal_level = hot_standby
    max_wal_senders = 5
    wal_keep_segments = 32
  replica.conf: hot_standby = on
  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust
    host    replication     replication     all                     md5
    host all all all md5
  postgres.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    dynamic_shared_memory_type = posix
    log_timezone = 'UTC'
    datestyle = 'iso, mdy'
    timezone = 'UTC'
    lc_messages = 'en_US.utf8'
    lc_monetary= 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'
    default_text_search_config = 'pg_catalog.english'
    include_if_exists = 'master_or_replica.conf'