apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- celery-worker-deployment.yaml
- celery-beat-deployment.yaml
- celery-flower-deployment.yaml
- service.yaml
# - hpa.yaml
patchesStrategicMerge:
- deployment-var.yaml
images:
- name: job_recommender
  newName: gcr.io/banded-totality-247701/job_recommender
  newTag: 'latest'
- name: gce-proxy
  newName: gcr.io/cloudsql-docker/gce-proxy
  newTag: '1.17'
configMapGenerator:
- name: celery-config
  files:
    - config/start-worker.sh
    - config/start-beat.sh
    - config/start-flower.sh
    - config/create-ssh-tunnel.sh
secretGenerator:
- name: gcp-credentials
  files:
    - secret/cloudsql-credentials.json
    - secret/storage-credentials.json
- name: mysql-sshkey
  files:
    - secret/mysql-sshkey
    - secret/mysql-sshkey.pub
    - secret/mysql-sshknown_hosts
generatorOptions:
  disableNameSuffixHash: true