apiVersion: v1
kind: Service
metadata:
  name: celery-flower
  labels:
    app: celery-flower
  annotations:
      cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: 5555
    targetPort: http
  selector:
    app: celery-flower
