apiVersion: v1
data:
  init.sh: "#!/bin/bash\nif [[ ${HOSTNAME} == 'redis-0' ]]; then\n\tredis-server /redis-config/master.conf\nelse\n\tredis-server
    /redis-config/slave.conf\nfi"
  master.conf: |-
    bind 0.0.0.0
    port 6379
    dir /redis-data
  slave.conf: |-
    bind 0.0.0.0
    port 6379
    dir .
    slaveof redis-0.redis 6379
kind: ConfigMap
metadata:
  labels:
    app: redis
  name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-read
spec:
  ports:
  - port: 6379
    targetPort: redis
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - command:
        - sh
        - -c
        - source /redis-config/init.sh
        image: redis:6.0.1-alpine
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /redis-config
          name: config
        - mountPath: /redis-data
          name: data
      priorityClassName: high-priority
      volumes:
      - configMap:
          defaultMode: 420
          name: redis-config
        name: config
      - emptyDir: {}
        name: data
