apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- statefulset.yaml
- service.yaml
commonLabels:
  app: postgres
images:
- name: postgres
  newName: postgres
  newTag: '10.5'
configMapGenerator:
- name: postgres-config
  files:
    - config/postgres.conf
    - config/pg_hba.conf
    - config/master.conf
    - config/replica.conf
    - config/init.sh
generatorOptions:
  disableNameSuffixHash: true